apiVersion: v1
kind: DeploymentConfig
metadata:
  name: omar-superoverlay-app
  namespace: omar-dev
  selfLink: /oapi/v1/namespaces/omar-dev/deploymentconfigs/omar-superoverlay-app
  uid: dce4d263-82c2-11e7-ba3b-0e704fd9c8b2
  resourceVersion: '9380824'
  generation: 941
  creationTimestamp: '2017-08-16T20:38:29Z'
  labels:
    app: omar-openshift
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - omar-superoverlay-app
        from:
          kind: ImageStreamTag
          namespace: o2
          name: 'omar-superoverlay-app:latest'
        lastTriggeredImage: >-
          172.30.181.173:5000/o2/omar-superoverlay-app@sha256:aa37823f110125951625852eb97de58521e1cacba34ef3fb0fdab9c018fc7ac3
  replicas: 1
  test: false
  selector:
    app: omar-openshift
    deploymentconfig: omar-superoverlay-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: omar-openshift
        deploymentconfig: omar-superoverlay-app
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: omar-superoverlay-app
          image: >-
            172.30.181.173:5000/o2/omar-superoverlay-app@sha256:aa37823f110125951625852eb97de58521e1cacba34ef3fb0fdab9c018fc7ac3
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_CLOUD_CONFIG_LABEL
              value: master
          resources: {}
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
status:
  latestVersion: 935
  observedGeneration: 941
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 1
  unavailableReplicas: 0
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: ImageStreamTag
            namespace: o2
            name: 'omar-superoverlay-app:latest'
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2017-10-31T18:15:52Z'
      lastTransitionTime: '2017-10-31T18:15:52Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2017-12-06T18:13:37Z'
      lastTransitionTime: '2017-12-06T18:13:35Z'
      reason: NewReplicationControllerAvailable
      message: >-
        replication controller "omar-superoverlay-app-935" successfully rolled
        out
  readyReplicas: 1
